#ifndef CONSTANTS_H
#define CONSTANTS_H

#define WINDOW_TITLE "Game of Life"
#define WINDOW_WIDTH 920
#define WINDOW_HEIGHT 720
#define SETTINGS_WIDTH 200
#define SETTINGS_HEIGHT 720
#define GRID_WIDTH 720
#define GRID_HEIGHT 720
#define CELL_WIDTH 10
#define CELL_HEIGHT 10
#define MIN_DELAY 5
#define MAX_DELAY 100

#endif
